/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.airliner;

import Business.Airplanes;
import Business.Fleet;
import Business.TravelAgent;
import Business.airlinerclass;
import Business.airlinerdirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pranjal
 */
public class ManagefleetJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagefleetJPanel
     */
    private JPanel userprocesscontainer;
    private airlinerclass al;
    private Fleet fleet;
    
   
    public ManagefleetJPanel(JPanel userprocesscontainer, airlinerclass al) {
         initComponents();
        this.userprocesscontainer=userprocesscontainer;
        this.al=al;
        this.fleet=al.getFleet();
        populateTable();
        
    }
    
       
        public void populateTable()
    {
    
    DefaultTableModel dtm=(DefaultTableModel)listofairplanestable.getModel();
        dtm.setRowCount(0);
        
        for(Airplanes airplanes:al.getFleet().getAirplanedirectory())
        {
                Object row[]=new Object[2];
                row[0]=airplanes;
                row[1]=airplanes.getNumberofseats();
                dtm.addRow(row);
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listofairplanestable = new javax.swing.JTable();
        addairplanebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();

        jLabel1.setText("AIRPLANES");

        listofairplanestable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "No.of seats"
            }
        ));
        jScrollPane1.setViewportView(listofairplanestable);

        addairplanebtn.setText("ADD");
        addairplanebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addairplanebtnActionPerformed(evt);
            }
        });

        deletebtn.setText("DELETE");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        backbtn.setText("BACK");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(191, 191, 191))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(addairplanebtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deletebtn)
                            .addGap(153, 153, 153)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backbtn)
                        .addGap(79, 79, 79))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addairplanebtn)
                    .addComponent(deletebtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(backbtn)
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        userprocesscontainer.remove(this);
        CardLayout layout = (CardLayout)userprocesscontainer.getLayout();
        layout.previous(userprocesscontainer);
    }//GEN-LAST:event_backbtnActionPerformed

    private void addairplanebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addairplanebtnActionPerformed
        // TODO add your handling code here:
         addairplaneJPanel newairplane = new addairplaneJPanel(userprocesscontainer, fleet);
        userprocesscontainer.add("addairplaneJPanel", newairplane);
        CardLayout layout = (CardLayout)userprocesscontainer.getLayout();
        layout.next(userprocesscontainer);
    }//GEN-LAST:event_addairplanebtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        int selectedrow=listofairplanestable.getSelectedRow();

        if (selectedrow < 0)
        {
            JOptionPane.showMessageDialog(null,"Please select any row");
        }
        else{
            int dialogbutton=JOptionPane.YES_NO_OPTION;
            int dialogresult=JOptionPane.showConfirmDialog(null, "will you like to delete this row?");
            if(dialogresult==JOptionPane.YES_OPTION);
            Airplanes airplanes=(Airplanes)listofairplanestable.getValueAt(selectedrow,0);
            al.getFleet().removeairplane(airplanes);
            JOptionPane.showMessageDialog(null, "Vital Sign has been deleted");
            populateTable();
        
        }
                        
        
       
    }//GEN-LAST:event_deletebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addairplanebtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listofairplanestable;
    // End of variables declaration//GEN-END:variables
}
