/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.TravelAgent;
import Interface.mainframe.BookSeatsJPanel;
import Interface.mainframe.ManageFlightsJPanel;
import Interface.mainframe.ManageairlinerJPanel;
import java.awt.CardLayout;

/**
 *
 * @author Rushabh
 */
public class MainJFrame extends javax.swing.JFrame {

    private TravelAgent travelagent;
    
//    private MasterOrderCatalog moc;
    
    /** Creates new form MainJFrame */
        public MainJFrame() {
        initComponents();
        //this.setExtendedState(MAXIMIZED_BOTH);
         travelagent = new TravelAgent();
//        moc = new MasterOrderCatalog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        userprocesscontainer = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        manageairlinerbtn = new javax.swing.JButton();
        BookSeatsBtn = new javax.swing.JButton();
        ManageFlightsBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userprocesscontainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userprocesscontainer);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageairlinerbtn.setText("Manage Airliner");
        manageairlinerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageairlinerbtnActionPerformed(evt);
            }
        });
        jPanel2.add(manageairlinerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 110, -1, -1));

        BookSeatsBtn.setText("Book Seats");
        BookSeatsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookSeatsBtnActionPerformed(evt);
            }
        });
        jPanel2.add(BookSeatsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        ManageFlightsBtn.setText("Manage Flights");
        ManageFlightsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageFlightsBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ManageFlightsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 290, -1, -1));

        jSplitPane1.setLeftComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageairlinerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageairlinerbtnActionPerformed
        // TODO add your handling code here:
         ManageairlinerJPanel airlinerpanel = new ManageairlinerJPanel(userprocesscontainer, travelagent.getAd());
        userprocesscontainer.add("ManageairlinerJPanel",airlinerpanel);
        CardLayout layout = (CardLayout)userprocesscontainer.getLayout();
        layout.next(userprocesscontainer);
    }//GEN-LAST:event_manageairlinerbtnActionPerformed

    private void BookSeatsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookSeatsBtnActionPerformed
        // TODO add your handling code here:
        BookSeatsJPanel bookingpanel = new BookSeatsJPanel(userprocesscontainer, travelagent.getCd(),travelagent.getMs(),travelagent);
        userprocesscontainer.add("BookSeatsJPanel",bookingpanel);
        CardLayout layout = (CardLayout)userprocesscontainer.getLayout();
        layout.next(userprocesscontainer);
    }//GEN-LAST:event_BookSeatsBtnActionPerformed

    private void ManageFlightsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageFlightsBtnActionPerformed
        // TODO add your handling code here:
        ManageFlightsJPanel manageflightjpanel = new ManageFlightsJPanel(userprocesscontainer, travelagent.getAd(), travelagent);
        userprocesscontainer.add("ManageFlightsJPanel",manageflightjpanel);
        CardLayout layout = (CardLayout)userprocesscontainer.getLayout();
        layout.next(userprocesscontainer);
        
    }//GEN-LAST:event_ManageFlightsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookSeatsBtn;
    private javax.swing.JButton ManageFlightsBtn;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton manageairlinerbtn;
    private javax.swing.JPanel userprocesscontainer;
    // End of variables declaration//GEN-END:variables
}
