/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.mainframe;

import Business.TravelAgent;
import Business.airlinerclass;
import Business.airlinerdirectory;
import Interface.airliner.AddairlinerJPanel;
import Interface.airliner.ManagefleetJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pranjal
 */
public class ManageairlinerJPanel extends javax.swing.JPanel {

    
     private JPanel userprocesscontainer;
     private airlinerdirectory ad;
    

    public ManageairlinerJPanel(JPanel userprocesscontainer, airlinerdirectory ad) {
        initComponents();
        this.userprocesscontainer=userprocesscontainer;
        this.ad=ad;
        populateTable();
        
    }
    
       
        public void populateTable()
    {
    
    DefaultTableModel dtm=(DefaultTableModel)Listofairlinerstable.getModel();
        dtm.setRowCount(0);
        
        for(airlinerclass airliner:ad.getairlinerDict())
        {
                Object row[]=new Object[1];
                row[0]=airliner;
                dtm.addRow(row);
        }
        
        
        

    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Listofairlinerstable = new javax.swing.JTable();
        Airlinerlabel = new javax.swing.JLabel();
        managefleetbtn = new javax.swing.JButton();
        addairlinerbtn = new javax.swing.JButton();
        deleteairlinerbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();

        Listofairlinerstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "      NAME"
            }
        ));
        jScrollPane1.setViewportView(Listofairlinerstable);

        Airlinerlabel.setText("AIRLINERS");

        managefleetbtn.setText("MANAGE FLEET");
        managefleetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managefleetbtnActionPerformed(evt);
            }
        });

        addairlinerbtn.setText("ADD");
        addairlinerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addairlinerbtnActionPerformed(evt);
            }
        });

        deleteairlinerbtn.setText("DELETE");
        deleteairlinerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteairlinerbtnActionPerformed(evt);
            }
        });

        backbtn.setText("BACK");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(Airlinerlabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(465, 465, 465)
                        .addComponent(deleteairlinerbtn)))
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(managefleetbtn)
                        .addGap(120, 120, 120)
                        .addComponent(addairlinerbtn)
                        .addGap(188, 188, 188))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backbtn)
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Airlinerlabel)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addairlinerbtn)
                    .addComponent(managefleetbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteairlinerbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(backbtn)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addairlinerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addairlinerbtnActionPerformed
        // TODO add your handling code here:
        AddairlinerJPanel newairliner = new AddairlinerJPanel(userprocesscontainer,ad );
        userprocesscontainer.add("AddairlinerJPanel", newairliner);
        CardLayout layout = (CardLayout)userprocesscontainer.getLayout();
        layout.next(userprocesscontainer);
              
    }//GEN-LAST:event_addairlinerbtnActionPerformed

    private void deleteairlinerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteairlinerbtnActionPerformed
        // TODO add your handling code here:
        int selectedrow=Listofairlinerstable.getSelectedRow();

        if (selectedrow < 0)
        {
            JOptionPane.showMessageDialog(null,"Please select any row");
        }
        else{
            int dialogbutton=JOptionPane.YES_NO_OPTION;
            int dialogresult=JOptionPane.showConfirmDialog(null, "will you like to delete this row?");
            if(dialogresult==JOptionPane.YES_OPTION);
            airlinerclass airliner=(airlinerclass)Listofairlinerstable.getValueAt(selectedrow,0);
            ad.removeairliner(airliner);
            JOptionPane.showMessageDialog(null, "Vital Sign has been deleted");
            populateTable();
        
        }
    }//GEN-LAST:event_deleteairlinerbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        userprocesscontainer.remove(this);
        CardLayout layout = (CardLayout)userprocesscontainer.getLayout();
        layout.previous(userprocesscontainer);
    }//GEN-LAST:event_backbtnActionPerformed

    private void managefleetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managefleetbtnActionPerformed
        
        // TODO add your handling code here:
        int getSelectedRow = Listofairlinerstable.getSelectedRow();
        if(getSelectedRow <0){
            JOptionPane.showMessageDialog(null, "No row selected");
        }else{
            airlinerclass al = (airlinerclass) Listofairlinerstable.getValueAt(getSelectedRow, 0);
        ManagefleetJPanel managefleet = new ManagefleetJPanel(userprocesscontainer, al);
        userprocesscontainer.add("ManagefleetJPanel", managefleet);
        CardLayout layout = (CardLayout)userprocesscontainer.getLayout();
        layout.next(userprocesscontainer);
        }
    }//GEN-LAST:event_managefleetbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Airlinerlabel;
    private javax.swing.JTable Listofairlinerstable;
    private javax.swing.JButton addairlinerbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton deleteairlinerbtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton managefleetbtn;
    // End of variables declaration//GEN-END:variables
}
