/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.flight;

import Business.Airplanes;
import Business.TravelAgent;
import Business.airlinerclass;
import Business.flightclass;
import Business.flightdirectoryclass;
import Interface.mainframe.ManageairlinerJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Pranjal
 */
public class AddFlightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateairlinerjPanel
     */
    private JPanel userprocesscontainer;
    private flightdirectoryclass fd;
    private airlinerclass a1;
    private TravelAgent ta;
    public AddFlightJPanel(JPanel userprocesscontainer, flightdirectoryclass fd , airlinerclass a1, TravelAgent ta) {
        initComponents();
        this.userprocesscontainer=userprocesscontainer;
        this.fd=fd;
        this.a1=a1;
        this.ta=ta;
         populateComboBox();

    }
    
    private void populateComboBox(){
        for(Airplanes ap: a1.getFleet().getAirplanedirectory()){
            airplanecombobox.addItem(ap.getAirplanename());
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        flightIDtextfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        flightnametextfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        SourceTextfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Destinationtextfield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        departuturetextfield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        arrivaltextfield = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        flightchargestextfield = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        airplanecombobox = new javax.swing.JComboBox<>();
        Datelabel = new javax.swing.JLabel();
        DateTextfield = new javax.swing.JTextField();

        jLabel1.setText("ADD FLIGHT");

        jLabel2.setText("Flight ID");

        jLabel3.setText("Flight Name");

        jLabel4.setText("Source");

        jLabel5.setText("Destination");

        jLabel6.setText("Departure");

        jLabel7.setText("Arrival ");

        jLabel8.setText("Flight Charges");

        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        jLabel9.setText("Airplane");

        Datelabel.setText("Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(addbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addComponent(BackBtn)
                .addGap(112, 112, 112))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(104, 104, 104))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Datelabel)
                                        .addGap(17, 17, 17)))
                                .addGap(107, 107, 107)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(airplanecombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(flightIDtextfield)
                            .addComponent(flightnametextfield)
                            .addComponent(SourceTextfield)
                            .addComponent(Destinationtextfield)
                            .addComponent(departuturetextfield)
                            .addComponent(arrivaltextfield)
                            .addComponent(flightchargestextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(DateTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(flightIDtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(flightnametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(SourceTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Destinationtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(departuturetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(arrivaltextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(flightchargestextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Datelabel)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(airplanecombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addbtn)
                            .addComponent(BackBtn)))
                    .addComponent(DateTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
               backAction();
    }                                            

    
      private void backAction() {
        userprocesscontainer.remove(this);
        Component[] componentArray = userprocesscontainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
       viewflightsJPanel viewflights = (viewflightsJPanel) component;
        viewflights.populateTable();
        CardLayout layout = (CardLayout) userprocesscontainer.getLayout();
        layout.previous(userprocesscontainer);
    
    }//GEN-LAST:event_BackBtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
         flightclass flight= fd.addflight();
        flight.setFlightID(flightIDtextfield.getText());
        flight.setFlightname(flightnametextfield.getText());
        flight.setSource(SourceTextfield.getText());
        flight.setDestination(Destinationtextfield.getText());
        flight.setDeparture(departuturetextfield.getText());
        flight.setArrival(arrivaltextfield.getText());
        flight.setFlightcharges(flightchargestextfield.getText());
        flight.setDate(DateTextfield.getText());
        String airplane=(String) airplanecombobox.getSelectedItem();
        Airplanes ap=null;
        for(Airplanes airp: a1.getFleet().getAirplanedirectory())
            if(airp.getAirplanename().equals(airplane)){
            ap=airp;
            }
        flight.setAirplane(ap);
        ta.getMs().addflight(flight);
        
        JOptionPane.showMessageDialog(null, "airliner successfully added", "Warning", JOptionPane.INFORMATION_MESSAGE);
          
        flightIDtextfield.setText("");
        flightnametextfield.setText("");
        SourceTextfield.setText("");
        Destinationtextfield.setText("");
        arrivaltextfield.setText("");
        departuturetextfield.setText("");
        flightchargestextfield.setText("");
        DateTextfield.setText("");
                
                                         

    }//GEN-LAST:event_addbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JTextField DateTextfield;
    private javax.swing.JLabel Datelabel;
    private javax.swing.JTextField Destinationtextfield;
    private javax.swing.JTextField SourceTextfield;
    private javax.swing.JButton addbtn;
    private javax.swing.JComboBox<String> airplanecombobox;
    private javax.swing.JTextField arrivaltextfield;
    private javax.swing.JTextField departuturetextfield;
    private javax.swing.JTextField flightIDtextfield;
    private javax.swing.JTextField flightchargestextfield;
    private javax.swing.JTextField flightnametextfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    
}
