/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.flight;

import Business.TravelAgent;
import Business.airlinerclass;
import Business.flightclass;
import Business.flightdirectoryclass;
import Interface.airliner.AddairlinerJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pranjal
 */
public class viewflightsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewflightsJPanel
     */
    private JPanel userprocesscontainer;
       private     airlinerclass a1;
       private flightdirectoryclass fd;
       private TravelAgent ta;
    public viewflightsJPanel(JPanel userprocesscontainer, airlinerclass a1, TravelAgent ta) {
        initComponents();
        this.userprocesscontainer=userprocesscontainer;
        this.a1=a1;
        this.fd= a1.getFlightdirectory();
        this.ta=ta;
        populateTable();
        
    }
    
       
        public void populateTable()
    {
    
    DefaultTableModel dtm=(DefaultTableModel)flighttable.getModel();
        dtm.setRowCount(0);
        
        for(flightclass flight:a1.getFlightdirectory().getFlightdirectory())
        {
                Object row[]=new Object[9];
                row[0]=flight;
                row[1]=flight.getFlightname();
                row[2]=flight.getSource();
                row[3]=flight.getDestination();
                row[4]=flight.getDeparture();
                row[5]=flight.getArrival();
                row[6]=flight.getFlightcharges();
                row[7]=flight.getAirplane();
                row[8]=flight.getDate();
                dtm.addRow(row);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        flighttable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        AddBtn = new javax.swing.JButton();
        updatebtninviewflights = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        savebtninviewflights = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        departuretextfield = new javax.swing.JTextField();
        arrivaltextfield = new javax.swing.JTextField();
        flightchargestextfield = new javax.swing.JTextField();
        flightidtextfield = new javax.swing.JTextField();
        flightnametextfield = new javax.swing.JTextField();
        destinationtextfield = new javax.swing.JTextField();
        sourcetextfield = new javax.swing.JTextField();
        DeleteBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        airplanecombobox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        Datetextfield = new javax.swing.JTextField();

        flighttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Flight ID", "Flight Name", "Source", "Destination", "Departure", "Arrival", "Flight Charges", "Airplane", "Date"
            }
        ));
        jScrollPane1.setViewportView(flighttable);

        jLabel1.setText("View Flights");

        AddBtn.setText("Add");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        updatebtninviewflights.setText("Update");
        updatebtninviewflights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtninviewflightsActionPerformed(evt);
            }
        });

        jLabel3.setText("Flight ID");

        jLabel4.setText("Flight Name");

        jLabel5.setText("Source");

        jLabel6.setText("Destination");

        savebtninviewflights.setText("Save");
        savebtninviewflights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtninviewflightsActionPerformed(evt);
            }
        });

        jLabel7.setText("Departure");

        jLabel8.setText("Arrival");

        jLabel9.setText("Flight Charges");

        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        arrivaltextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrivaltextfieldActionPerformed(evt);
            }
        });

        flightidtextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightidtextfieldActionPerformed(evt);
            }
        });

        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Airplane");

        airplanecombobox.setEnabled(false);
        airplanecombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airplanecomboboxActionPerformed(evt);
            }
        });

        jLabel10.setText("Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(flightidtextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                    .addComponent(flightnametextfield)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sourcetextfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(destinationtextfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Datetextfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(214, 214, 214)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(savebtninviewflights))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(departuretextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(flightchargestextfield)
                                    .addComponent(arrivaltextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(airplanecombobox, 0, 108, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(277, 277, 277)
                                .addComponent(jLabel2)
                                .addGap(210, 210, 210)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DeleteBtn)
                        .addGap(50, 50, 50)
                        .addComponent(updatebtninviewflights)
                        .addGap(53, 53, 53)
                        .addComponent(AddBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backbtn)))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddBtn)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DeleteBtn)
                        .addComponent(updatebtninviewflights)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(flightidtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(departuretextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(flightnametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(arrivaltextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sourcetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(airplanecombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(flightchargestextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backbtn)
                            .addComponent(jLabel10)
                            .addComponent(Datetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(destinationtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(savebtninviewflights)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void flightidtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightidtextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightidtextfieldActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
        int selectedrow= flighttable.getSelectedRow();

        if (selectedrow <0)
        {
            JOptionPane.showMessageDialog(null,"Please select any row");
            }
        else{
             flightclass fs= (flightclass)flighttable.getValueAt(selectedrow, 0);
            fd.deleteflight(fs);
            ta.getMs().deleteflight(fs);
            
            JOptionPane.showMessageDialog(null, "Flight has been deleted");
            populateTable();
        }
       

        
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        AddFlightJPanel newflight = new AddFlightJPanel(userprocesscontainer,fd,a1,ta );
        userprocesscontainer.add("AddFlightJPanel", newflight);
        CardLayout layout = (CardLayout)userprocesscontainer.getLayout();
        layout.next(userprocesscontainer);
    }//GEN-LAST:event_AddBtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        userprocesscontainer.remove(this);
        CardLayout layout = (CardLayout)userprocesscontainer.getLayout();
        layout.previous(userprocesscontainer);
    }//GEN-LAST:event_backbtnActionPerformed

    private void updatebtninviewflightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtninviewflightsActionPerformed
        // TODO add your handling code here:
        int selectedRow = flighttable.getSelectedRow();
        if(selectedRow <0){
            JOptionPane.showMessageDialog(null, "No row selected");
        }else{
        flightclass updatedflights= (flightclass)flighttable.getValueAt(selectedRow, 0);
        
        flightidtextfield.setText(updatedflights.getFlightID());
        flightnametextfield.setText(updatedflights.getFlightname());
        sourcetextfield.setText(updatedflights.getSource());
        destinationtextfield.setText(updatedflights.getDestination());
        departuretextfield.setText(updatedflights.getDeparture());
        arrivaltextfield.setText(updatedflights.getArrival());
        flightchargestextfield.setText(updatedflights.getFlightcharges());
        Datetextfield.setText(updatedflights.getDate());
     
        
        
        updatebtninviewflights.setVisible(false);
        savebtninviewflights.setVisible(true);
        }
    }//GEN-LAST:event_updatebtninviewflightsActionPerformed

    private void savebtninviewflightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtninviewflightsActionPerformed
        // TODO add your handling code here:
        int selectedRow = flighttable.getSelectedRow();
        flightclass updatedflights= (flightclass)flighttable.getValueAt(selectedRow, 0);
        updatedflights.setFlightID(flightidtextfield.getText());
        updatedflights.setFlightname(flightnametextfield.getText());
        updatedflights.setSource(sourcetextfield.getText());
        updatedflights.setDestination(destinationtextfield.getText());
        updatedflights.setDeparture(departuretextfield.getText());
        updatedflights.setArrival(arrivaltextfield.getText());
        updatedflights.setFlightcharges(flightchargestextfield.getText());
        updatedflights.setDate(Datetextfield.getText());
        
        
        
        
       
        populateTable();
        
        flightidtextfield.setText("");
        flightnametextfield.setText("");
        sourcetextfield.setText("");
        destinationtextfield.setText("");
        departuretextfield.setText("");
        arrivaltextfield.setText("");
        flightchargestextfield.setText("");
        Datetextfield.setText("");
        
        JOptionPane.showMessageDialog(null, "Update Successfull");
        
        updatebtninviewflights.setVisible(true);
        savebtninviewflights.setVisible(false);
    }//GEN-LAST:event_savebtninviewflightsActionPerformed

    private void airplanecomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airplanecomboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airplanecomboboxActionPerformed

    private void arrivaltextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrivaltextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrivaltextfieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JTextField Datetextfield;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JComboBox<String> airplanecombobox;
    private javax.swing.JTextField arrivaltextfield;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField departuretextfield;
    private javax.swing.JTextField destinationtextfield;
    private javax.swing.JTextField flightchargestextfield;
    private javax.swing.JTextField flightidtextfield;
    private javax.swing.JTextField flightnametextfield;
    private javax.swing.JTable flighttable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton savebtninviewflights;
    private javax.swing.JTextField sourcetextfield;
    private javax.swing.JButton updatebtninviewflights;
    // End of variables declaration//GEN-END:variables
}
